"""Initial_migration_sqlite

Revision ID: 85ff5408fee4
Revises: 
Create Date: 2026-02-20 09:17:19.787352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ff5408fee4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_api_key_hash'), 'api_keys', ['api_key_hash'], unique=True)
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_origin', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('clothing_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_type', sa.Enum('tops', 'bottoms', 'outerwear', name='categorytype'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fit_adjustments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('fit_style', sa.Enum('slim', 'regular', 'relaxed', 'oversized', name='fitstyle'), nullable=False),
    sa.Column('chest_adjustment_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('waist_adjustment_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('hip_adjustment_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['clothing_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('size_charts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('region', sa.Enum('US', 'UK', 'EU', 'India', 'Asia', name='region'), nullable=False),
    sa.Column('fit_style', sa.Enum('slim', 'regular', 'relaxed', 'oversized', name='fitstyle'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['clothing_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chest_cm', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('waist_cm', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('hip_cm', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('shoulder_width_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('preferred_fit', sa.Enum('slim', 'regular', 'relaxed', 'oversized', name='fitpreference'), nullable=False),
    sa.Column('measurement_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('size_chart_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_size', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('fit_style_used', sa.String(), nullable=True),
    sa.Column('measurement_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['clothing_categories.id'], ),
    sa.ForeignKeyConstraint(['size_chart_id'], ['size_charts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('size_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('size_chart_id', sa.Uuid(), nullable=False),
    sa.Column('size_label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('chest_min_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('chest_max_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('waist_min_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('waist_max_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('hip_min_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('hip_max_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('shoulder_min_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('shoulder_max_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('length_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['size_chart_id'], ['size_charts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purchased', sa.Boolean(), nullable=True),
    sa.Column('fit_result', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('size_measurements')
    op.drop_table('recommendations')
    op.drop_table('user_measurements')
    op.drop_table('size_charts')
    op.drop_table('fit_adjustments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('clothing_categories')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_api_keys_api_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
